# Generated by Django 5.2.6 on 2025-09-27 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=20)),
                ('game_level', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EEGReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('attention', models.FloatField()),
                ('meditation', models.FloatField()),
                ('delta', models.FloatField()),
                ('theta', models.FloatField()),
                ('low_alpha', models.FloatField()),
                ('high_alpha', models.FloatField()),
                ('low_beta', models.FloatField()),
                ('high_beta', models.FloatField()),
                ('low_gamma', models.FloatField()),
                ('mid_gamma', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='gamesession.session')),
            ],
        ),
    ]
